export const ACTION = {
    DEAD: -1,
    STAND: 0,
    RUN_JUMP: 1,
    HANG_CLIMB: 2,
    IN_MIDAIR: 3,
    FREE_FALL: 4,
    BUMP: 5,
    HANG_STRAIGHT: 6,
    TURN: 7
}

export const LEVEL = {
    DUNGEON: 0,
    PALACE: 1
}

export const TILE = {
    SPACE: 0,
    FLOOR: 1,
    SPIKES: 2,
    PILLAR: 3,
    GATE: 4,
    STUCK_BUTTON: 5,
    DROP_BUTTON: 6,
    TAPESTRY: 7,
    BOTTOM_BIG_PILLAR: 8,
    TOP_BIG_PILLAR: 9,
    POTION: 10,
    LOOSE_BOARD: 11,
    TAPESTRY_TOP: 12,
    MIRROR: 13,
    DEBRIS: 14,
    RAISE_BUTTON: 15,
    EXIT_LEFT: 16,
    EXIT_RIGHT: 17,
    CHOPPER: 18,
    TORCH: 19,
    WALL: 20,
    SKELETON: 21,
    SWORD: 22,
    BALCONY_LEFT: 23,
    BALCONY_RIGHT: 24,
    LATTICE_PILLAR: 25,
    LATTICE_SUPPORT: 26,
    SMALL_LATTICE: 27,
    LATTICE_LEFT: 28,
    LATTICE_RIGHT: 29,
    TORCH_WITH_DEBRIS: 30,
    NULL: 31
}